microsoft/planetary-computer-tasks

deployment/helm/deploy-values.template.yaml, deployment/helm/published/pctasks-server/templates/deployment.yaml, deployment/helm/published/pctasks-server/values.yaml, deployment/terraform/batch_pool/providers.tf, deployment/terraform/resources/aks.tf, deployment/terraform/resources/apim.tf, deployment/terraform/resources/ip.tf, deployment/terraform/resources/keyvault.tf, deployment/terraform/resources/output.tf, deployment/terraform/resources/providers.tf, deployment/terraform/resources/values.tfvars.template, deployment/terraform/resources/variables.tf, deployment/terraform/staging/main.tf, deployment/terraform/staging/variables.tf, pctasks/server/pctasks/server/request.py, pctasks/server/pctasks/server/settings.py
This change adds an access key that can be used to validate the origin of incoming requests. This allows route-based restrictions on request forwarding for routes that have scoped access.
=> Add feature to validate proxy

Dockerfile.dev, docs/settings.md, pctasks/client/pctasks/client/client.py, pctasks/client/pctasks/client/profile.py, pctasks/client/pctasks/client/records/cli.py, pctasks/client/pctasks/client/records/commands/_fetch.py, pctasks/client/pctasks/client/records/commands/_status.py, pctasks/client/pctasks/client/records/commands/fetch.py, pctasks/client/pctasks/client/records/commands/status.py, pctasks/client/pctasks/client/records/render.py, pctasks/client/pctasks/client/settings.py, pctasks/client/pctasks/client/submit/_cli.py, pctasks/client/pctasks/client/utils.py, pctasks/core/pctasks/core/models/api.py, pctasks/core/pctasks/core/models/record.py, pctasks/core/pctasks/core/models/workflow.py, pctasks/core/pctasks/core/settings.py, pctasks/dataset/pctasks/dataset/_cli.py, pctasks/ingest/pctasks/ingest/_cli.py
This PR makes two changes:
- Adds a command `pctasks record status` to report status of a workflow and all it's child jobs and tasks. It includes a `--watch` option that uses rich's `Live` console printer to refresh status as a job executes.
- Adds `default_args` to client settings, and the functionality for creating and editing them in the `pctasks profile [create|edit]` command. This allows for default arguments to be passed to workflows when the workflow asks for the argument and it is not supplied via another means. This is useful for per-profile arguments - the instigating example was the `registry` argument which needed to be provided on the command line each time, but really was a way to abstract a single workflow over different environments. By setting a default argument for …
=> Add record status command; add default args in settings

datasets/chesapeake_lulc/collection/chesapeake-lc-13/template.json, datasets/chesapeake_lulc/collection/chesapeake-lc-7/template.json, datasets/chesapeake_lulc/collection/chesapeake-lu/template.json
Added the geoparquet assets to the collection templates for the chesapeake dataset:
- chesapeake-lc-7
- chesapeake-lc-13
- chesapeake-lu
Not tested
None completed.
=> fix: add geoparquet assets to the chesapeake collection templates

pctasks/core/pctasks/core/models/event.py, pctasks/core/pctasks/core/models/record.py, pctasks/core/pctasks/core/models/task.py, pctasks/core/pctasks/core/models/utils.py, pctasks/core/pctasks/core/tables/base.py, pctasks/core/tests/models/test_task.py, pctasks/core/tests/tables/test_record.py, pctasks/operations/setup.py
Fixes a few issues with the Records API
* `created` (or any model attribute with a default value) will be included in JSON serialized output
* Makes serializable dates in API responses time zone aware
* Fixes package name typo
Run record responses now look like this:
```
{
"links": null,
"errors": null,
"created": "2022-08-18T15:43:15.465446+00:00",
"updated": "2022-08-18T15:43:30.503287+00:00",
"status": "completed",
"dataset": "microsoft/test-remote-1",
"run_id": "1d8409a51631431daa3f145064d37561",
"workflow": null,
"trigger_event": null,
"args": null
},
```
New test + local testing
=> Fix Record API dates and model fields

datasets/deltaresfloods/tests/test_tasks.py, pctasks/dataset/tests/test_dataset.py, pctasks/dev/pctasks/dev/mocks.py, pctasks/run/pctasks/run/_cli.py, pctasks/run/pctasks/run/workflow/executor/simple.py, pctasks/task/pctasks/task/context.py
This adds a TaskContext.run_id field to the TaskContext class. This will
enable downstream tasks to include the run id in their logs / outputs.
Every `TaskContext` create through `task/run.py:run_task` has a pretty clear run ID. Some of the other ones just kind of have to be made up. I think that's fine for tests. I'm a bit worried about it for things like `SimpleWorkflowRunner` which, IIUC, don't have a natural run ID associated with them.
Not at all
=> ENH: Added TaskContext.run_id

pctasks/dev/pctasks/dev/test_utils.py
Integration test fails due to expectation of user confirmation of workflow submission. Run `./scripts/console integration-tests` and then `scripts/bin/test-integration` for failure.
Tests pass.
=> fix: remove test_dataset expectation of workflow submit confirmation

.github/workflows/pr.yml, cluster/dev-values.yaml, deployment/helm/published/pctasks-server/templates/deployment.yaml, deployment/helm/published/pctasks-server/values.yaml
Fix an issue with a dev setting not being set in the Helm chart for pctasks-server, which was causing integration tests to fial.
Also fix typo in GH Actions workflow for PRs that was causing integration tests not to run on PRs against main.
=> Fix integration tests

deployment/helm/argo-values.yaml
Maybe fixes the Kubernetes RBAC issues we were seeing. The server is using a ServiceAcount `pctasks-sa`, but Helm / argo is creating a RoleBinding for the name `argo-workflows`. Maybe specifying it here will fix things?
=> Specify service account name

deployment/terraform/staging/main.tf
The AKS cluster that's deployed as part of CI/CD was manually change to have 2 nodes. Previous terraform deploys have failed due to an inability to drain those nodes. Bumping the terraform up to 2 nodes, which can be moved back down to 1 if need be after the problem node is manually debugged.
=> Adjust node count on AKS cluster

docs/getting_started/dev_workflows.md
Small docs fix.
Manually:
```sh
$ pctasks records status workflow --watch b948177655b94ce7a3ab4b5f484a0bae
___   ___  _____            _
| _ \ / __||_   _| __ _  ___| |__ ___
|  _/| (__   | |  / _` |(_-/| / /(_-/
|_|   \___|  |_|  \__/_|/__/|_\_\/__/
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃                                     ┃ status          ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ Workflow: List log files in Azurite │ 🏃 Running      │
│  - Job: list-logs-job               │  🏃 Running     │
│     - Task:list-logs-task           │   🕖 Submitting │
└─────────────────────────────────────┴─────────────────┘
```
=> Fix docs, it's `records status`, not `records show`

pctasks/run/pctasks/run/_cli.py, pctasks/run/pctasks/run/cli.py
On **main**, the following command fails:
```sh
$ pctasks run local examples/list-logs.yaml
___   ___  _____            _
| _ \ / __||_   _| __ _  ___| |__ ___
|  _/| (__   | |  / _` |(_-/| / /(_-/
|_|   \___|  |_|  \__/_|/__/|_\_\/__/
Traceback (most recent call last):
File "/Users/gadomski/.virtualenvs/planetary-computer-tasks/bin/pctasks", line 33, in <module>
sys.exit(load_entry_point('pctasks.cli', 'console_scripts', 'pctasks')())
File "/Users/gadomski/Code/planetary-computer-tasks/pctasks/cli/pctasks/cli/cli.py", line 134, in cli
pctasks_cmd(prog_name="pctasks")
File "/Users/gadomski/.virtualenvs/planetary-computer-tasks/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File …
```
=> Fix args argument for CLI run functions

pctasks/core/pctasks/core/models/base.py, pctasks/run/pctasks/run/template.py, pctasks/run/tests/test_template.py
This adds a configuration option to `ForEachConfig` to optionally not flatten lists of lists. The default (True) preserves the existing behavior.
My use-case is an upstream task returning a `list[tuple[start, end]]`. The downstream uses a foreach to parallelize over this list, and each task needs the `(start, end)` tuple to work on the correct subset of the items.
=> Add option to not flatten foreach lists

pctasks/core/setup.py
Relaxes the pin on stac-validator, to make it possible to solve in an environment with stactools / stac-check. xref https://github.com/stac-utils/stac-check/issues/88, which discusses the pin in stac-check to 3.2.0.
=> [core]: relax pin on stac-validator

pctasks/client/pctasks/client/client.py
I spotted a 503 error when polling the task status endpoint with my client:
```pytb
File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pctasks/client/records/commands/status.py", line 30, in fetch_workflow_cmd
ctx.exit(_status.workflow_status_cmd(ctx, run_id, dataset, watch))
File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pctasks/client/records/commands/_status.py", line 73, in workflow_status_cmd
table, is_complete = get_table()
File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pctasks/client/records/commands/_status.py", line 46, in get_table
for job in sorted(client.get_jobs(run_id), key=lambda j: j.created):
File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pctasks/client/client.py", line …
```
=> [client]: Wrap client API requests in with_backoff

datasets/chesapeake_lulc/dataset.yaml, datasets/deltaresfloods/dataset.yaml, datasets/io-land-cover/dataset.yaml, datasets/noaa_nclimgrid/dataset.yaml, datasets/sentinel-1-grd/dataset.yaml, datasets/sentinel-3/dataset.yaml, datasets/sentinel-5p/dataset.yaml, pctasks/client/pctasks/client/runs/_status.py, pctasks/client/pctasks/client/utils.py, pctasks/core/pctasks/core/models/run.py, pctasks/run/pctasks/run/task/batch.py, pctasks/run/pctasks/run/workflow/executor/remote.py, scripts/publish
This is a follow up to #54 which fixes an issue where batch tasks did not include the job partition ID, which was breaking fan-out. It also improves the ability to handle initial task submission failures, and introduces a "skipped" job status which occurs if there are no partitions to run, and does not fail the workflow.
=> Fix batch task IDs, allow skipping jobs with no partitions

pctasks/core/pctasks/core/utils/backoff.py, pctasks/core/tests/utils/test_utils.py
While running tests locally, I noticed kubernetes killing the server pod
```
❯ kubectl -n pc get events | grep -i kil
26s         Normal    Killing             pod/pctasks-server-6f9fc7dd45-tdqds                      Container pctasks-server failed liveness probe, will be restarted
12m         Normal    Killing             pod/pctasks-server-78d5997f66-lc5js                      Container pctasks-server failed liveness probe, will be restarted
```
This, in turn, failed the tests when it attempted to make an HTTP request to the server:
```
if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://host.docker.internal:8500/tasks/runs/33de2707-f2ed-40c9-a4ac-162d67658d9f
```
I don't …
=> [client]: retry on 503 errors

deployment/requirements.txt, docker-compose.yml, pctasks/ingest_task/setup.py
Updates the pgstac dependency to 0.6.9, to match the version currently deployed to staging.
=> [ingest]: Bump pgstac to 0.6.9

deployment/bin/publish_func, deployment/helm/published/pctasks-server/templates/deployment.yaml, docker-compose.console.yml, docker-compose.yml, pctasks/client/pctasks/client/workflow/commands.py, pctasks/core/pctasks/core/models/run.py, pctasks/dataset/pctasks/dataset/_cli.py, pctasks/dataset/pctasks/dataset/cli.py, pctasks/dataset/pctasks/dataset/models.py, pctasks/dataset/pctasks/dataset/utils.py, pctasks/run/pctasks/run/batch/client.py, pctasks/run/pctasks/run/models.py, pctasks/run/pctasks/run/task/argo.py, pctasks/run/pctasks/run/task/base.py, pctasks/run/pctasks/run/task/batch.py, pctasks/run/pctasks/run/task/local.py, pctasks/run/pctasks/run/task/prepare.py, pctasks/run/pctasks/run/workflow/executor/models.py, pctasks/run/pctasks/run/workflow/executor/remote.py, pctasks/run/pctasks/run/workflow/local.py, pctasks/run/tests/test_messages.py, scripts/cluster, scripts/env
The main change in this PR is to allow batch jobs to be created before Job Partitions are generated, and manually terminated as part of a cleanup step in the remote workflow executor. This required refactoring the task preparation step, splitting out the fetching of image-key information and templating of secrets from the per-task configuration generated. This has the added benefit of reducing reads to keyvault and the Azure Tables storaging the image key data.
Other changes are minor and documented in commits.
=> Create and manually terminate Azure Batch jobs per job definition

deployment/cosmosdb/scripts/stored_procs/workflow-runs/bulkput-workflowruns.js, deployment/terraform/resources/cosmosdb.tf, pctasks/core/pctasks/core/cosmos/container.py, pctasks/core/pctasks/core/cosmos/containers/workflow_runs.py, pctasks/core/pctasks/core/cosmos/settings.py, pctasks/core/tests/cosmos/containers/test_workflow_runs.py, pctasks/dataset/pctasks/dataset/items/task.py, pctasks/run/pctasks/run/batch/client.py, pctasks/run/pctasks/run/task/argo.py, pctasks/run/pctasks/run/task/base.py, pctasks/run/pctasks/run/task/batch.py, pctasks/run/pctasks/run/task/local.py, pctasks/run/pctasks/run/workflow/executor/models.py, pctasks/run/pctasks/run/workflow/executor/remote.py, scripts/setup
This PR:
- Adds a bulk_put method on containers, which allows a stored procedure to do bulk inserts into CosmosDB. This optimizes the creation of JobPartitionRunRecord in remote.py
- Move from polling individual tasks to querying for failed tasks. This puts less pressure on the Azure Batch API for workflows that have many partitions.
- Logs during the create-items tasks to show speed of each individual item creation and progress through the chunk file.
=> Reduce API calls on Azure Batch and CosmosDB

datasets/noaa_nclimgrid/collection/noaa-nclimgrid-daily-prelim/template.json, datasets/noaa_nclimgrid/collection/noaa-nclimgrid-daily-scaled/template.json, datasets/noaa_nclimgrid/collection/noaa-nclimgrid-monthly/description.md, datasets/noaa_nclimgrid/collection/noaa-nclimgrid-monthly/template.json, datasets/noaa_nclimgrid/noaa_nclimgrid.py
We're planning to create a new collection to catalog the source NetCDF assets. Once that collection is ready we'll add links to the source as `via` relations.
For now, we'll drop those assets from the items produced by the stactools package.
cc @pjhartzell
(this is untested at the moment; Will test once my networking stuff is sorted out)
=> [noaa-nclimgrid]: Drop source NetCDF assets

pctasks/dataset/pctasks/dataset/chunks/models.py, pctasks/dataset/tests/test_dataset.py
Previously `--use-existing-chunkset` was failing with errors about the task not recieving the right arguments. I think this is because the wrong task name was used.
Fixes #68 
=> [dataset] Fixed ingest --use-existing-chunkset

datasets/noaa-mrms-qpe/README.md, datasets/noaa-mrms-qpe/workflows/update-noaa-mrms-qpe-1h-pass1.yaml, datasets/noaa-mrms-qpe/workflows/update-noaa-mrms-qpe-1h-pass2.yaml, datasets/noaa-mrms-qpe/workflows/update-noaa-mrms-qpe-24h-pass2.yaml, docs/getting_started/creating_a_dataset.md, pctasks/dataset/pctasks/dataset/_cli.py, pctasks/dataset/pctasks/dataset/cli.py, pctasks/dataset/pctasks/dataset/workflow.py, pctasks/dataset/tests/test_dataset.py
This is a bit of a hack, but it's a relatively small change to generate an "update" workflow from a dataset.yaml.
When you pass `--is-update`, this will
1. Append a `--since` argument to the workflow arguments
2. Inject the string literal `"${{ args.since }}"` for the `since` argument to the create-splits task. Then, when the update is later run with a concrete `--since` that concrete value will be templated in.
Combine that with a chunkset ID that also contains the literal `${{ args.since }}` and I think we have everything we need for dynamic updates.
This PR includes update workflows for noaa-mrms-qpe as an example.
`pctasks workflow submit noaa_mrms_qpe-noaa-mrms-qpe-1h-pass1-process-items-update --arg registry …
=> [dataset/QPE]: Add flag to generate update workflows

deployment/terraform/dev/pools.tf, deployment/terraform/staging/pools.tf, docs/getting_started/creating_a_dataset.md, pctasks/dataset/pctasks/dataset/models.py, pctasks/dataset/pctasks/dataset/workflow.py, pctasks/dataset/tests/data-files/datasets/test-dataset.yaml, pctasks/dataset/tests/test_dataset.py
Adds a `task_config` dictionary to the `DatasetDefinition` model to enable adding tags to tasks. The tags are parsed from the `task_config` dictionary and added to the appropriate tasks during workflow creation.
The tags are defined in a `task_config` object in the dataset yaml files. For example, a `batch_pool_id` tag can be added to the `create-items` task of a workflow by adding the following to the dataset yaml:
```
task_config:
create-items:
tags:
batch_pool_id: high_memory_pool
```
Added a tests to verify that tags specified in a dataset yaml are added to the `DataseDefinition` class and the appropriate workflow tasks.
=> Specify the batch pool id through task tags defined in a dataset yaml file

deployment/terraform/dev/pools.tf, deployment/terraform/resources/batch.tf, deployment/terraform/resources/storage_account.tf, deployment/terraform/staging/pools.tf
Sets the account-level flag for storage accounts to private, in addition to the container-level settings.
=> [deploy] Make batch accounts private

datasets/noaa-mrms-qpe/Dockerfile, datasets/noaa-mrms-qpe/dataset.yaml, datasets/noaa-mrms-qpe/workflows/update-noaa-mrms-qpe-1h-pass1.yaml, datasets/noaa-mrms-qpe/workflows/update-noaa-mrms-qpe-1h-pass2.yaml, datasets/noaa-mrms-qpe/workflows/update-noaa-mrms-qpe-24h-pass2.yaml, deployment/terraform/dev/pools.tf, deployment/terraform/staging/pools.tf
Our nightly job had some failures, ending with
```
File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 454, in _error_catcher
raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```
i.e. our runtime pip install failed. Moving this to a pre-built container with all the dependencies.
=> [noaa-mrms-qpe] Use pre-built Dockerfile

deployment/terraform/dev/pools.tf, deployment/terraform/staging/pools.tf
1. terraform didn't like the name change.
2. batch doesn't support D4_v4. Switched to D4_V3.
=> [deploy] fixed s2 pool deployment

Dockerfile.task_base, docs/user_guide/runtime.md, pctasks/core/pctasks/core/importer.py, pctasks/core/tests/storage/test_importer.py
This change moves uploaded code to the front of sys.path, effectively overwriting any existing code with newly uploaded code. IMO, this is the more expected behavior.
=> [core]: Prioritize uploaded code on sys.path

pctasks/core/pctasks/core/storage/blob.py, pctasks/core/tests/storage/test_blob.py
pctasks `BlobStorage.download_file` can hang indefinitely. This PR adds a `timeout_seconds` option to the `download_file` method that gets passed through to the Azure SDK to force an error for hanging downloads.
- I was not able to create a test that failed (download takes longer than minimum timeout, which is in integer seconds) via the azurite tools available in `pctasks.dev.blob`
- I empirically tested the timeout on Azure blobs of a few tens of MB, and it performs as desired: you can cause a `download_file` call to fail with a very short `timeout_seconds` of 1 or 2 seconds. Increase to 10 seconds and the download succeeds.
- I added a test to pctasks > core > tests > storage > test_blob.py that partially recreates the `download_file` method …
=> Add timeout option for BlobStorage.download_file

datasets/noaa-climate-normals/collection/noaa-climate-normals-gridded/template.json, datasets/noaa-climate-normals/collection/noaa-climate-normals-netcdf/template.json, datasets/noaa-climate-normals/collection/noaa-climate-normals-tabular/template.json, datasets/noaa-climate-normals/dataset.yaml, datasets/noaa-climate-normals/requirements.txt
The extra property fields (e.g., `noaa_climate_normals:period`, `noaa-climate-normals:frequency`) were missing the prefix `noaa_climate_normals` in the Collection templates and Item creation. This was fixed in the stactools package and the corrections propagated into pctasks via this PR. 
- New Items for the `netcdf` and `gridded` Collections were created and ingested into PC Test to validate the correction.
- Due to the extended Item creation time for `tabular` data, new tabular Items were not created and ingested into PC Test. The corrections to the tabular Items can be seen in the stactools package [examples](https://github.com/stactools-packages/noaa-climate-normals/tree/main/examples/noaa-climate-normals-tabular) and will be realized when …
=> NOAA Climate Normals: Add missing custom field prefix

datasets/noaa-mrms-qpe/collection/noaa-mrms-qpe-24h-pass2/template.json
Corrects pass (was 1, now 2) and period (was 1, now 24) in the summaries section of the noaa-mrms-qpe-24h-pass2 collection template.
Fixes https://github.com/microsoft/PlanetaryComputerDataCatalog/issues/390
Not tested. 
=> Correct pass and period in noaa-mrms-qpe-24h-pass2 collection summaries

datasets/goes/goes-cmi/collection/description.md, datasets/goes/goes-cmi/collection/template.json
This adds goes-18 to the platforms, and slightly modifies the description to reference goes-18.
xref https://github.com/stactools-packages/goes/pull/32.
=> Added goes-18

pctasks/core/pctasks/core/cosmos/container.py
Followup to https://github.com/microsoft/planetary-computer-tasks/pull/98, adding this in one more spot.
```
[INFO] 2023-01-11 23:30:44,968 - (BATCH CLIENT) Adding BatchJob usda-cdl-process-chunk-a329f653--cf2-929a-7eec75c881e9-tsk_db_bl
[INFO] 2023-01-11 23:30:45,091 -  - Running 52 job partitions
[INFO] 2023-01-11 23:30:45,092 -  - Preparing jobs...
[INFO] 2023-01-11 23:30:47,934 -  - Submitting initial tasks...
[INFO] 2023-01-11 23:30:48,248 -  -  Initial tasks submitted, checking status...
[ERROR] 2023-01-11 23:30:53,895 - Failed to update task status: (429) Message: {"Errors":["Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429"]}
ActivityId: …
```
=> Retry cosmos put

.github/workflows/cicd.yml
CI was failing on main because of an expired secret. This connects GitHub Actions to Azure using the guide at
https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux.
I set up the federated identity for our Service Principal. I added those secrets (AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID) to our GitHub Actions repository secrets.
=> Use federated identity for GHA/Azure

datasets/esa-cci-lc/Dockerfile, datasets/esa-cci-lc/README.md, datasets/esa-cci-lc/collection/esa-cci-lc-netcdf/template.json, datasets/esa-cci-lc/dataset.yaml
- Added container image (will be removed in #104)
- Remove Microsoft as processor for netcdf collection
- set production values for ingest
=> [esa-cci-lc] Staging fixups

datasets/usda-cdl/requirements.txt
Update `stactools-usda-cdl` dependency to pick up https://github.com/stactools-packages/usda-cdl/commit/78c9e8ffb01685d465315c6fb5af49667ac59a59.
I've re-tiled the data and the staging explorer looks better? I can't quite be sure b/c there's still some edge effects at far-out zoom but that should just be caching issues, many mid-level zooms look good.
=> Bump stactools-usda-cdl to v0.1.2

pctasks/ingest/pctasks/ingest/_cli.py, pctasks/ingest/pctasks/ingest/cli.py, pctasks/ingest/pctasks/ingest/models.py, pctasks/ingest_task/tests/test_items.py
This changes the output of `pctasks ingest ndjsons` to include the commonly (always?) needed service principal credentials.
For example:
```
$ pctasks ingest ndjsons usgs-lcmap-conus-v13 blob://landcoverdata/lcmap-etl-data/lcmap-conus-v13/2023-01-12-full-3/items/all --workflow-id=lcmap-conus-v13-reingest
```
Will now produce
```yaml
name: Ingest NDJsons from blob://landcoverdata/lcmap-etl-data/lcmap-conus-v13/2023-01-12-full-3/items/all
jobs:
ingest-items:
id: ingest-items
tasks:
- id: ingest-ndjson
image_key: ingest
task: pctasks.ingest_task.task:ingest_task
args:
content:
type: Ndjson
ndjson_folder:
uri: blob://landcoverdata/lcmap-etl-data/lcmap-conus-v13/2023-01-12-full-3/items/all
extensions: []
options:
insert_group_size: 5000
insert_only: false
environment:
AZURE_TENANT_ID: ${{ …
```
=> Add service principal secrets to item ingest task

datasets/goes/goes-glm/README.md, datasets/goes/goes-glm/dataset.yaml, datasets/goes/goes-glm/requirements.txt, datasets/goes/goes-glm/workflows/goes-glm-update.yaml, pctasks/core/setup.py
stactools-goes-glm==0.2.3 added support for goes-18. This bumps its version in our image and adds an entry to look for goes-glm assets in the `noaa-goes18` storage container.
=> [goes-glm]: Added goes-18

scripts/cideploy
This mounts ~/.azure into the docker container doing the deployment. We now get credentials from the Azure CLI, which are stored in ~/.azure on the GitHub runner. By mounting the directory to `/root/.azure` on the docker container deploying things, it too has access to the Azure credentials from the azlogin action.
=> [CI]: Mount the azure directory in deploy

pctasks/client/pctasks/client/runs/_status.py, pctasks/core/pctasks/core/storage/blob.py, pctasks/core/pctasks/core/utils/backoff.py, pctasks/run/pctasks/run/workflow/executor/remote.py
This fixes a bug where the poll rate for `pctasks runs status --watch` was mishandled; the default of "Poll once every 10 seconds" was being interpreted as "Poll 10 times every second". 
Also, consolidate the number of ComosDB connections created in the workflow executor. This passes container clients to threads in the thread pool rather than create new connections per thread. As far as I can tell and have tested, the client is thread safe, and there is text in the ComsosDB docs that suggests the number of client connections should be minimized.
Additionally, modified the standard exception inspection in "with_backoff" to recurse down into inner exceptions, and added some additional logic to catch 'connection reset by peer' errors. This is based on a transient error I saw fail a Task …
=> Fix status --watch poll rate; reduce the number of ComosDB client connections

deployment/bin/lib, pctasks/core/pctasks/core/queues.py, pctasks/core/setup.py, pctasks/dev/pctasks/dev/azurite.py, pctasks/run/pctasks/run/_cli.py, pctasks/run/pctasks/run/batch/client.py, pctasks/run/pctasks/run/settings.py, pctasks/run/pctasks/run/task/argo.py, pctasks/run/pctasks/run/task/base.py, pctasks/run/pctasks/run/task/batch.py, pctasks/run/pctasks/run/task/local.py, pctasks/run/pctasks/run/workflow/executor/remote.py, pctasks/run/pctasks/run/workflow/local.py, pctasks/run/tests/workflow/test_remote.py
This PR provides improvements on how PCTasks utilizes Azure Batch. This includes reducing the number of Batch clients created and the number of times the API is hit during a workflow run.
It modifies the RemoteWorkflowExecutor and TaskRunner to be context managers so that things like client connections can be managed by the class. The BatchTaskRunner now creates a batch client and uses a single client instead of creating and closing clients per call. This client is used across multiple threads, and thread safety from the client is assumed. This has been tested in multiple runs of a ~50 partition workflow.
In addition, a thread-locked cache is used to minimize the Batch API calls in the method that find failed Batch tasks. This method was being called once per thread, normally at roughly …
=> Consolidate Batch client usage and decrease API hits

datasets/goes/goes-glm/Dockerfile, datasets/goes/goes-glm/dataset.yaml, pctasks/core/pctasks/core/queues.py, pctasks/dev/pctasks/dev/azurite.py
Compared to 3.8, Python 3.11 has some fixes to deadlocks in ssl. This updates the version used in the goes-glm task.
=> [goes-glm]: Update to Python 3.11

deployment/bin/deploy
This will test whether GitHub is able to deploy with the mounted /root/.azure login credentials for deployment. Currently this line was attempting to login with the service principal, which is now unset.
=> Update deploy to avoid az login

.github/workflows/cicd.yml, deployment/bin/deploy, deployment/bin/lib, deployment/docker-compose.yml, deployment/terraform/dev/pools.tf, deployment/terraform/staging/pools.tf, scripts/cideploy
This reverts changes to using a federated identity, as that method hasn't been working for our CI deploy. Mounting
the ~/.azure directory into the container did not work
for containerized deployment. We'll continue to use
a service principal for this.
=> Use service principal in deployment

deployment/terraform/resources/keyvault.tf
To disable public access to the KV of the pc-tasks, the kv terraform script was modified to only permit connections from trusted services, allowlisted IP addresses, and the vnet of the k8s nodes.
Compliance security of the pc tasks kvs
=> Change kv access settings

deployment/bin/deploy, deployment/bin/kv_add_ip, deployment/bin/kv_rmv_ip, deployment/docker-compose.yml, deployment/terraform/dev/env.sh, deployment/terraform/staging/env.sh
During [deploy](https://github.com/microsoft/planetary-computer-tasks/blob/main/deployment/bin/deploy), terraform requires access to a KV to retrieve secrets from two different Key Vaults ([1](https://github.com/microsoft/planetary-computer-tasks/blob/0f47e4f88062b62f547f28c44b6195952996ffc2/deployment/terraform/resources/keyvault.tf#L1-L42) & [2](https://github.com/microsoft/planetary-computer-tasks/blob/0f47e4f88062b62f547f28c44b6195952996ffc2/deployment/terraform/resources/keyvault.tf#L44-L59)). Said KVs have to update their firewall rule to only **"Allow public access from specific virtual networks and IP addresses"**.
The current changes are meant to authenticate as an Azure Service Principal and include the current runner public IP into the KVs firewall allow list.
Once the task is …
=> Kv firewall

datasets/esa-worldcover/Dockerfile, datasets/esa-worldcover/README.md, datasets/esa-worldcover/collection/description.md, datasets/esa-worldcover/collection/template.json, datasets/esa-worldcover/dataset.yaml, datasets/esa-worldcover/esa_worldcover.py, datasets/esa-worldcover/requirements.txt, datasets/esa-worldcover/workflows/esa-worldcover-process-items-2020.yaml, datasets/esa-worldcover/workflows/esa-worldcover-process-items-2021.yaml
Adds the ESA WorldCover dataset, including version 1 (2020 data) and version 2 (2021 data). Note that 2020 STAC already exists in the PC via the old ETL pipeline. 
- STAC Collection and description updated to include the new 2021 data
- Uses a raster footprint for the Item geometries (2020 Items in production use the tile boundary)
- Adds the grid extension to the STAC Items (2020 Items in production do not have this)
- Adds the "InputQuality" asset (2020 Items in production do not have this)
_It is expected that the existing 2020 Items will be reprocessed to use a raster footprint geometry, add the grid extension, and add the InputQuality asset._
PC Test Links:
- [STAC Collection](https://pct-apis-staging.westeurope.cloudapp.azure.com/stac/collections/esa-worldcover)
- [Data Catalog …
=> Add ESA WorldCover

docker-compose.yml
This bumps the version of azurite used to 3.23.0. Newer versions of azure.storage are using an API version not supported by the older azurite.
=> [core]: Update azurite version

datasets/goes/goes-glm/workflows/goes-glm-update.yaml
1. Use the container image update added in https://github.com/microsoft/planetary-computer-tasks/pull/148/
2. Remove the retired goes-17 block
=> [goes-glm]: Updated workflow definition

docs/reference/api.md, pctasks/core/pctasks/core/storage/blob.py, pctasks/core/tests/storage/test_blob.py
In the low-latency branch, EventGrid gives us urls like `https://<account>.blob.core.windows.net/<container>/<path>`. The create items function expect `blob://<account>/<container>/<path>` URLs. This function implements that.
I didn't *see* this implemented anywhere, but I might have missed it.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> [core]: Add helper to rewrite blob storage urls

pctasks/core/pctasks/core/utils/backoff.py, pctasks/core/tests/utils/test_utils.py
Fixes a failure observed in a goes-glm pipeline, where a blob download failed with an IncompleteReadError.
<details>
```pytb
[INFO] 2023-04-13 08:37:31,756 -  === PCTasks: Task Failed! ===
[ERROR] 2023-04-13 08:37:31,756 - Failed to create item from blob://goeseuwest/noaa-goes18/GLM-L2-LCFA/2023/082/06/OR_GLM-L2-LCFA_G18_s20230820622000_e20230820622200_c20230820622220.nc
Traceback (most recent call last):
File "/opt/conda/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
yield
File "/opt/conda/lib/python3.11/site-packages/urllib3/response.py", line 593, in read
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(113691 bytes read, 190053 more expected)
During handling of the above exception, …
```
=> [core]: Retry on IncompleteReadError

pctasks/core/setup.py, pctasks/dev/setup.py, pctasks/ingest_task/setup.py, pctasks/run/setup.py, pctasks/server/setup.py
Various packages included invalid requirements like
">=3.1.*".
I've replaced those with the equivalent expansions like
>=3.1.0,<3.2
Note: I don't think that pctasks should be setting upper bounds *anywhere* in its requirements (and so no exact pins. Lower bounds are fine). Instead, specific deployments of pctasks should be pinning their requirements.
Fixes the build failure in https://github.com/microsoft/planetary-computer-tasks/actions/runs/4720818604/jobs/8373333525#step:5:7874.
=> [packaging]: Fixed install_requires

datasets/goes/goes-glm/dataset.yaml
This bumps the version of pctasks in the goes-glm container image, to include the fixes from #175.
It also removes the goes-17 container, since that's not operational anymore.
=> [goes-glm]: Bump container image

pctasks/client/pctasks/client/client.py, pctasks/core/pctasks/core/importer.py, pctasks/core/pctasks/core/storage/base.py, pctasks/core/tests/storage/test_importer.py
This reimplements code upload for directories to avoid PyZipFile.writepy. It (deliberately) uploads `.pyc` files, which imposes a strong constraint that the version of Python running submit on the client matches the version of Python running in the task.
Instead, we replicate PyZipFile.writepy's behavior, but we upload `.py` files rather than `.pyc`. The zip-based importer works with both `.py` and `.pyc` files.
=> [core]: Avoid PyZipFile in code upload

datasets/goes/goes-glm/dataset.yaml, datasets/goes/goes-glm/goes_glm.py, datasets/goes/goes-glm/workflows/goes-glm-update.yaml
In a recent run, we experience the hanging goes-glm task again. Here's the backtrace from py-spy on the hanging process.
```
Thread 1 (active): "MainThread"
read (ssl.py:1134)
recv_into (ssl.py:1278)
readinto (socket.py:706)
read (http/client.py:466)
_fp_read (urllib3/response.py:533)
read (urllib3/response.py:567)
stream (urllib3/response.py:628)
generate (requests/models.py:816)
__next__ (core/pipeline/transport/_requests_basic.py:173)
process_content (blob/_download.py:52)
_initial_request (blob/_download.py:435)
__init__ (blob/_download.py:349)
download_blob (blob/_blob_client.py:848)
wrapper_use_tracer (core/tracing/decorator.py:76)
<lambda> (core/storage/blob.py:514)
with_backoff (core/utils/backoff.py:142)
download_file (core/storage/blob.py:513)
create_item (goes_glm.py:38) …
```
=> [goes-glm]: Try to fix with socket timeout

deployment/terraform/resources/keyvault.tf, pctasks/dataset/pctasks/dataset/items/task.py, pctasks/dataset/setup.py, pctasks/dataset/tests/items/test_task.py, requirements-dev.txt
This adds some tracing to monitor item creating time to the create_item task. After an item is created, we'll log a messaage to an application insights instance with some custom dimensions
* `type`: `pctasks.create_item` for filtering
* `collection_id`: The collection ID, for filtering
* `asset_uri`: unique(ish) identifier for what assets were cataloged
* `duration_seconds`: The time it took to create the item
For collections to use this, they just need to include `APPLICATIONINSIGHTS_CONNECTION_STRING` in the `environment` section of the dataset.yaml. We might consider automatically loading that into the environment.
=> [dataset]: Added tracing to create_item

datasets/ms-buildings/collection/description.md, datasets/ms-buildings/collection/template.json, datasets/ms-buildings/dataset.yaml, datasets/ms-buildings/ms_buildings.py, datasets/ms-buildings/requirements.txt, docs/user_guide/chunking.md, pctasks/dataset/pctasks/dataset/chunks/task.py, pctasks/dataset/pctasks/dataset/models.py
This updates the `ms-buildings` collection for some recent data and STAC metadata updates / changes.
The newest set of data (2023-04-25) have been rewritten in delta format, which offers scalable metadata handling (specifically partitioning and statistics, which can speed up access times to avoid touching large numbers of files in Blob Storage).
I've added a link to the delta table as a new collection-level asset (will update the example notebook shortly)
This also updates to the latest version of `stactools-msbuildings`, which
1. targets quadkey level items, rather than region level. This will make spatial searchers more useful
2. adds an `msbuildings:processing-date` property
Finally, I've added a pctasks task for creating the STAC items. Older items were created out of band and …
=> Updated ms-buildings

datasets/cil-gdpcir/collection/cil-gdpcir-cc-by/description.md, datasets/cil-gdpcir/collection/cil-gdpcir-cc0/description.md, datasets/cil-gdpcir/dataset.yaml
Followup to ca07f78a-508d-4c29-9f74-35d60a36e75e. pctasks adds a trailing `/` the `name_starts_with`. We can use two `uri`s instead.
=> [cil-gdpcir] Fixed listing for cc-by

.github/workflows/pr.yml, cluster/kind-config.yaml
In https://github.com/microsoft/planetary-computer-tasks/pull/201, we're adding KEDA for scaling the streaming pipelines. KEDA currently requires Kubernetes 1.24.
This updates the `kind` action to a version compatible with Kubernetes 1.24 and newer, and bumps the Kubernetes version we're using.
=> Update `helm/kind-action`  version

datasets/goes/goes-glm/workflows/goes-glm-update.yaml
This bumps the goes-glm pipeline to a new version, picking up the newer version of azure-storage-blob unlocked in
https://github.com/microsoft/planetary-computer-tasks/pull/193.
=> [goes-glm]: Updated dependencies

pctasks/client/pctasks/client/client.py, pctasks/client/pctasks/client/workflow/commands.py, pctasks/dataset/pctasks/dataset/_cli.py, pctasks/dataset/pctasks/dataset/cli.py, pctasks/dataset/pctasks/dataset/utils.py
This adds a `-y` option to the dataset commands that allows skipping of user input for submitting workflows. This is useful for e.g. iterating over collections to submit ingest commands:
```shell
> pctasks dataset list-collections -d datasets/sentinel-3/dataset.yaml | xargs -I {} \
pctasks dataset ingest-collection -d datasets/sentinel-3/dataset.yaml -c {} -s -y
```
=> Add option to auto-confirm submits in dataset cli

.github/workflows/cicd.yml, deployment/terraform/staging/variables.tf
Currently, the `deploy` stage of CD is failing after https://github.com/microsoft/planetary-computer-tasks/pull/186 thanks to the `username` terraform variable not being set (e.g. https://github.com/microsoft/planetary-computer-tasks/actions/runs/5329010562/jobs/9654894797).
This PR sets it to `staging` in the GitHub Actions file.
=> Set `username` for CI/CD deployment

deployment/terraform/dev/main.tf, deployment/terraform/dev/variables.tf, deployment/terraform/resources/apim.tf, deployment/terraform/resources/variables.tf, deployment/terraform/staging/main.tf, deployment/terraform/staging/variables.tf
This adds a new variable to the deployment to set the [API management SKU name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management#sku_name). The default is set to `Standard_1` (no change). We set it to `Consumption_0` for our test / dev envs.
I'm testing a deploy to `dev` now.
=> Added terraform variable to set API Management sku_name

datasets/sentinel-1-grd/s1grd.py, datasets/sentinel-1-grd/test_s1grd.py
In addition to creating the STAC item, we also write out the JSON to another storage container for another processing pipeline.
=> [sentinel-1-grd]: Write out STAC items

datasets/goes/goes-cmi/Dockerfile, datasets/goes/goes-cmi/README.md, datasets/goes/goes-cmi/dataset.yaml, datasets/goes/goes-cmi/goes_cmi/goes_cmi.py, datasets/goes/goes-cmi/goes_cmi/goes_errors.py, datasets/goes/goes-cmi/goes_cmi/goes_paths.py, datasets/goes/goes-cmi/requirements.txt
Adds the `goes-cmi` Collection.
- Created `goes-cmi` Items via pctasks.
- I am unable to ingest Items into PC Test. I deleted the `goes-cmi` Items and the Collection from PC Test. But am running into a known [pgstac issue](https://github.com/stac-utils/pgstac/issues/185) where ingesting a Collection after deleting a Collection with the same id causes Item ingest to fail.
- Checked for equivalence to production Items by diffing an Item from the production API against one produced with this PR. 
- Ran `isort` and `black` against the Python files. Note that `scripts/format` does not touch files in the `datasets` directory.
- Docker image built and pushed to both `pccomponents` and `pccomponentstest` registries.
Please delete options that are not …
=> migrate goes-cmi

datasets/modis/dataset.yaml
This adjusts the splitting for modis to generate fewer chunks. Previously, we would generate ~35 create-chunks per collection, which would overwhelm the storage account when all were running at once.
Now we'll spend a bit more time during the listing / chunk creation stage, since it won't be as parallelized.
The item creation shouldn't slowed down, since we still have the chunk-length setting (which we can adjust). It might be faster since we're creating fewer small chunks.
=> [modis]: Adjust splitting

datasets/sentinel-1-grd/s1grd.py
This removes a try/except in s1-grd that was silencing real errors.
```
$ pctasks runs get task-log 5748c0ed-092d-472d-bab5-1a982699cf37 process-chunk create-items
[ERROR] 2023-07-07 13:41:37,629 - Missing file when attempting to create item for blob://sentinel1euwest/s1-grd/GRD/2023/7/5/IW/DV/S1A_IW_GRDH_1SDV_20230705T170135_20230705T170200_049291_05ED53_649F/manifest.safe
Traceback (most recent call last):
File "/mnt/batch/tasks/workitems/sentinel-1-grd-process-chunk-574-2d-bab5-1a982699cf37-tsk_gen_gr/job-1/create-items-0/wd/_code/s1grd.py", line 141, in create_item
item: pystac.Item = create_item(
File "/opt/conda/lib/python3.8/site-packages/stactools/sentinel1/grd/stac.py", line 101, in create_item
metalinks = MetadataLinks(
File …
```
=> Error loudly in s1-grd

pctasks/dataset/pctasks/dataset/workflow.py, pctasks/dataset/tests/test_dataset.py
Previously, `--is-update-workflow` would only add the `--since` argument to the first `input` in the `create-splits` task. Workflows like modis, with multiple inputs, would try recreating STAC items for every item for the later inputs under `asset_storage`.
=> [dataset]: Fixed update workflow with multi-input

Dockerfile.dev, Dockerfile.task_base, docker-compose.aux.yml, docker-compose.yml, docs/development/setup.md, pctasks/.dockerignore, pctasks/run/Dockerfile, pctasks/server/Dockerfile, scripts/update
* moved pctasks-frontend to an aux server
* shrink container images a bit
Trying to fix the CI failures at https://github.com/microsoft/planetary-computer-tasks/actions/runs/5579847626/jobs/10195946932#step:11:419, where we seem to be running out of disk space.
```
--- ErrImagePull: rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5001/pctasks-ingest:latest": failed to extract layer sha256:d32bc1b36f4802dd6c638c4501c6eb836f140b71383c0d5e87db50115060811a: write /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/285/fs/opt/az/lib/python3.10/site-packages/azure/synapse/artifacts/models/__pycache__/_models_py3.cpython-310.pyc: no space left on device: unknown
[419](https://github.com/microsoft/planetary-computer-tasks/actions/runs/5579847626/jobs/10 …
```
=> [CI]: Update container images

Dockerfile.task_base, pctasks/ingest_task/Dockerfile, pctasks/run/Dockerfile, requirements-task-base.txt
This PR optimzies the various task images (task-base, run, and ingest). It removes *a bunch* of stuff, some of which is probably needed for at least some of our pipelines.
I'm going to do an audit of which pipelines are using which images. I'm also a bit unsure about what sorts of issues are going to be picked up by CI. We might need additional testing to be confident that this doesn't break anything.
Here's the size comparison:
| image             | before | after |
| ----------------- | ------ | ----- |
| pctasks-ingest    | 1.3GB  | 257MB |
| pctasks-run       | 630MB  | 290MB |
| pctasks-task-base | 3.32   | 373MB |
=> Optimize task images

datasets/ecmwf-forecast/dataset.yaml
Updated yaml to catch different directory naming conventions as seen on 6/29.
Ran:
pctasks dataset process-items -d datasets/ecmwf-forecast/dataset.yaml test-20230629 --no-ingest --upsert --submit
against the following blob: blob://ai4edataeuwest/ecmwf/20230629/00z/0p4-beta/
Got the attached .csv. No mention of -opendata.
[uris-list.csv](https://github.com/microsoft/planetary-computer-tasks/files/12099656/uris-list.csv)
=> Updating YAML to account for -opendata in ECMWF directories

deployment/bin/publish_pkgs
In https://github.com/microsoft/planetary-computer-tasks/pull/243/, I made some updates to the scripts to allow configuring the CONF_DIR (default /opt/conf) and the directory for the pctasks source (/opt/src).
That implicilty requied calling `setup_env` anywhere you call the bash functions that do the publishing. This updates the GHA that does the function publishing to call setup_env.
=> [ci/cd]: Fix GHA publishing functions

datasets/goes/goes-cmi/streaming.yaml, deployment/terraform/resources/aks.tf, pctasks/ingest_task/setup.py
This adds a streaming workflow for goes-cmi. It's running in the staging-test deployment:
```
» curl -s
"https://pct-apis-staging.westeurope.cloudapp.azure.com/stac/collections/goes-cmi/items?limit=1"
| jq -r .features[0].properties.datetime
2023-07-25T20:23:55.4Z
```
While tuning the CPU and memory requests for this task, I noticed that we were using a different VM size on the streaming tasks than what we're using on the batch tasks. I think those should match, so I updated streaming to be `D3_v2`.
`goes-cmi` had some bad partitioning state left around in the pct database. We've updated `pctasks.ingest` to depend on `pgstac==0.7.10`
=> [low-latency]: Added goes-cmi

datasets/goes/goes-cmi/streaming.yaml, datasets/goes/goes-glm/streaming.yaml, deployment/terraform/resources/aks.tf, docs/user_guide/streaming.md, pctasks/run/pctasks/run/workflow/kubernetes.py, pctasks/run/tests/workflow/test_kubernetes.py, pctasks/task/pctasks/task/streaming.py
Adds support for using spot instances for streaming tasks.
We add a new node pool to AKS. Same worker type, but has spot priority and the required node labels and taints.
Adds the `allow_spot_instances` to the streaming task workflow definition. By default, spot nodes are not allowed. I think only regular nodes should be used for high-priority tasks like ingesting into the database.
For lower-priority tasks, like creating COGs, and maybe creating STAC items, we can use spot nodes.
The Kubernetes scheduling *should* be set up to just prefer spot nodes when scheduling a Pod. If none are available, it should fall back to regular nodes, but that will need to be confirmed.
=> Allow spot instances for streaming tasks.

datasets/goes/goes-cmi/streaming.yaml, datasets/goes/goes-glm/streaming.yaml, docs/user_guide/streaming.md, pctasks/dataset/pctasks/dataset/streaming.py
Puts the streaming `create_item` call inside a `traced_create_item` context to ensure that we emit metrics on how long it took to run.
=> Added metrics for streaming create items

pctasks_funcs/PublishItemsCF/__init__.py, pctasks_funcs/StorageEventsCF/__init__.py, pctasks_funcs/StorageEventsQueue/__init__.py
This adds some more structured logging to the Azure Functions supporting low-latency pipelines. I intend to build some monitoring and dashboards on top of these messages.
Unfortunately, the Azure Functions runtime overwrites any properties we put in `{extra: {custom_dimensions: ...}}`. So as a workaround we'll put the structured message in the `message` field as JSON and parse that in the queries.
Here's an example query:
````kql
traces
| filter operation_Name == "StorageEventsQueue"
| filter message hasprefix "{"
| project timestamp, message=parse_json(message)
| filter message.type == "storage-event"
| order by timestamp desc
| limit 10
```
=> Structured logs for low-latency functions

pctasks_funcs/StorageEventsCF/__init__.py
We were including this as a tuple in the log message, not a plain string.
=> Fixed `url` format in log messages

deployment/terraform/resources/function.tf, docs/user_guide/streaming.md, pctasks_funcs/tests/test_storage_events.py
This fixes the dispatch rules in goes-cmi to match what we have for its `dataset.yaml`. We match the `MCMIP{C,M,F}` prefix.
We *may* want to introduce a `PCTASKS_DISPATCH__<NAME>__REGEX` concept, which would enable terser rules for dispatch. This  didn't quite warrant that I think.
=> [goes-cmi]: Fixed dispatch rules

deployment/terraform/resources/aks.tf
Updates the terraform configuration to use Azure Linux on the AKS node pools.
=> [deploy]: Use Azure Linux on AKS node pools

deployment/terraform/staging/main.tf
According to the AKS documentation, k8s version 1.25.6 is no longer supported. This change upgrades to 1.26.6.
```
> az aks get-versions --location westeurope --output table
KubernetesVersion    Upgrades
-------------------  ------------------------
1.28.3               None available
1.28.0               1.28.3
1.27.7               1.28.0, 1.28.3
1.27.3               1.27.7, 1.28.0, 1.28.3
1.26.10              1.27.3, 1.27.7
1.26.6               1.26.10, 1.27.3, 1.27.7
1.25.15              1.26.6, 1.26.10
1.25.11              1.25.15, 1.26.6, 1.26.10
```
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration …
=> Upgrade k8s version

deployment/terraform/resources/apim.tf, deployment/terraform/resources/ip.tf, deployment/terraform/resources/vnet.tf, deployment/terraform/staging/main.tf, deployment/terraform/staging/output.tf, deployment/terraform/staging/pools.tf, deployment/terraform/staging/variables.tf
Configures APIM to use an [external network](https://learn.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet?tabs=stv2). Essentially this deploys the APIM VM instances into the AKS virtual network and creates a new public IP for APIM. 
This is necessary to comply with Azure internal network security policies.
=> Configure APIM to use external network

deployment/bin/deploy, deployment/bin/lib, deployment/terraform/resources/aks.tf, deployment/terraform/resources/apim.tf, deployment/terraform/resources/output.tf, deployment/terraform/resources/variables.tf
APIM cannot connect to the public IP of the cluster, therefore we have to use an internal ingress controller to establish network communication.
`curl https://planetarycomputer-test.microsoft.com/tasks` returns an object from the PCTasks API
=> Use internal K8S load balancer

Dockerfile.task_base, pctasks/ingest_task/Dockerfile, pctasks/run/Dockerfile, pctasks/server/Dockerfile
The base docker image contains a version of `setuptools` with a vulnerability that must be addressed.
Built the dockerfiles. The fear was that installing a newer `setuptools` would break the container builds but that did not happen.
=> Add pip install for setuptools>=65.5.1 in Dockerfiles

datasets/ecmwf-forecast/Dockerfile, datasets/ecmwf-forecast/README.md, datasets/ecmwf-forecast/dataset.yaml, datasets/ecmwf-forecast/ecmwf_forecast.py, datasets/ecmwf-forecast/requirements.txt, datasets/ecmwf-forecast/test_ecmwf_forecast.py
ECMWF is now publishing data at 0.25 (km?) resolution, but our code was not considering asset resolution so we were failing to ingest 1 out of 2 assets for each scene (either them 0.4 succeeder or the 0.25 succeeded, but not both). This change updates the Planetary Computer dataset task for EMCWF to consume the updated `stactools-packages/ecmwf-forecast` STAC tool in [this branch](https://github.com/stactools-packages/ecmwf-forecast/tree/0.2.0)
Fixes #284 
Tested with UnitTests in the ECMWF-Forecast 
=> Update ECMWF forecast dataset to handle new resolution

pctasks/server/setup.py
This addresses [GHSA-2jv5-9r88-3w3p](https://github.com/advisories/GHSA-2jv5-9r88-3w3p)
Unit tests have been ran though `python-multipart` is used by FastAPI internally and not by us.
=> Upgrade python-multipart

.github/workflows/cicd.yml, deployment/Dockerfile, deployment/bin/deploy, deployment/bin/lib, deployment/docker-compose.yml, deployment/terraform/batch_pool/providers.tf, deployment/terraform/resources/keyvault.tf, deployment/terraform/resources/providers.tf, deployment/terraform/staging/backend.tf
The motivation of this PR is to remove the client secret in the GitHub actions workflow file cicd.yml to improve security. 
To do this, I reference this [page](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#add-federated-credentials) and use the federated credentials in service principal which allows authentication without the need for explicit client secret and made corresponding changes to authentication in the workflow.
This PR introduces basically the same code changes as in this [PR](https://github.com/microsoft/planetary-computer-apis/pull/208).
I created federated credential for this branch `user/elay/remove-client-secret`, so it can use the service principal to authenticate to …
=> Remove secret from cicd

.github/workflows/publish-charts-dev.yml, .github/workflows/publish-charts.yml
The default permissions for Github actions changed at some point and we now need to explicitly grant the job `contents: write` permissions so that it can push a commit to the `gh-pages` branch with the Helm charts to be consumed by OpenPC.
Refs:
1. [What is the GITHUB_TOKEN, is it a secret? Sort of, but not one we have to stop using.](https://docs.github.com/en/actions/security-guides/automatic-token-authentication).
2. [What permissions do actions have?](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#about-github-actions-permissions-for-your-repository)
3. [How did you know contents: write was the right thing to …
=> Fix Helm chart publishing permissions

deployment/terraform/dev/main.tf, deployment/terraform/dev/pools.tf, deployment/terraform/dev/variables.tf, deployment/terraform/resources/variables.tf, deployment/terraform/staging/main.tf, deployment/terraform/staging/variables.tf, docs/development/deploying.md
I missed a few SP refernces in the terraform. The deployment previously succeeded because these unused values were in the tfvars, but I've since removed them.
=> Removed task_acr_sp references in deployment

pctasks/core/pctasks/core/cosmos/container.py, pctasks/core/pctasks/core/cosmos/settings.py, pctasks/core/setup.py
This fixes the
ValueError: continuation tokens are not supported for cross-partition queries.
seen in the server, thanks to
https://github.com/Azure/azure-sdk-for-python/pull/29366.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Updated azure-cosmos-version

datasets/ecmwf-forecast/collection/template.json
Fixed a typo in the `msft:storage_account` for ecmwf-forecast.
=> Fixed typo in ecmwf metadata

datasets/ecmwf-forecast/dataset.yaml, pctasks/core/pctasks/core/storage/base.py, pctasks/core/pctasks/core/storage/blob.py, pctasks/core/pctasks/core/storage/local.py, pctasks/core/tests/storage/test_blob.py, pctasks/core/tests/storage/test_local.py, pctasks/dataset/pctasks/dataset/chunks/task.py, pctasks/dataset/pctasks/dataset/models.py
This adds a parameter to `Storage.walk`, allowing users to specif whether the `matches` applies just to the filename or to the full path, including the filename.
The same keyword is added to the task and task input, to let this be set in the datasset.yaml.
Recent changes to the data published in the ecmwf container requires a new feature in pctasks' create-chunks: the ability to match on a full path rather than just a filename.
Data are being published under both the
- <date-prefix>/ifs/...
- <date-prefix>/aifs/...
We list both sets of data, but our stactools package can't handle the aifs data properly yet. So we want to filter it out.
Previously, `matches` could only target the filename being listed. We need that to filter to specific products. We want to extend that match expression to …
=> [ENH]: Allow for matching on the full path

datasets/ecmwf-forecast/dataset.yaml
This rebuilds the ecmwf-forecast image, which is needed for the new `match_full_path` feature to work.
=> Updated ecmwf-forecast image

datasets/sentinel-2/README.md, datasets/sentinel-2/dataset.yaml, datasets/stac-geoparquet/README.md
Adds docs for how these workflows were added to the database.
=> Document stac-geoparquet and sentinel-2-l2a workflow creation
