microsoft/planetary-computer-tasks

- .gitignore
- deployment/Dockerfile
- deployment/bin/get_tfvars
- deployment/bin/lib
- deployment/terraform/resources/aks.tf
Adds the required RBAC settings for the kubernetes cluster and kubelogin for access during deploy.
> Add Azure AD RBAC to cluster

- scripts/cideploy
> Fix CI deployment - update path in cideploy script

- deployment/terraform/resources/apim.tf
KV values must be set as secret. Fixes CI deploy issue
> Set APIM named value as secret when coming from kv

- deployment/terraform/resources/apim.tf
Ensure all APIM named values are created before applying the policy that references them.
> Create named values before applying APIM policy

- deployment/terraform/resources/function.tf
> Disable FTP access to function app

- datasets/goes/goes-glm/README.md
- datasets/goes/goes-glm/workflows/goes-glm-update.yaml
Only list assets under 2022 for goes-glm updates.
> [goes-glm]: Optimize listing

- deployment/terraform/dev/pools.tf
- deployment/terraform/staging/pools.tf
1. Bump high-memory to 32 GB
2. Added landsat pool
> Update batch pools

- docs/conf.py
- docs/development/faq.md
- docs/development/setup.md
- docs/getting_started/creating_a_dataset.md
- docs/getting_started/dev_workflows.md
- docs/user_guide/templating.md
- docs/user_guide/workflows.md
Minor documentation fixups, including broken cross-doc references and missing `_static` directory. There's also some whitespace changes from my linter -- IMO it's worth linting markdown, but lmk if that's not desired and I can remove the whitespace changes.
Built docs locally w/o any warnings/errors.
> Minor doc fixes

- deployment/terraform/dev/pools.tf
- deployment/terraform/staging/pools.tf
- set to d8a_v4
- 5 tasks per node
> Updated s2 pool

- datasets/usgs-lcmap/Dockerfile
- datasets/usgs-lcmap/dataset.yaml
* Containerized
* Updated chunking
> [usgs-lcmap] Production fixups

- datasets/fws-nwi/collection/description.md
- datasets/fws-nwi/dataset.yaml
- datasets/fws-nwi/fws_nwi.py
* containerized
* Updated description
* fixed source location
> [fws-nwi]: Production fixups

- docker-compose.yml
- pctasks/ingest_task/setup.py
Update PGStac to 0.6.12 from 0.6.9
> Update PGStac to 0.6.12

- datasets/noaa-climate-normals/collection/noaa-climate-normals-gridded/description.md
- datasets/noaa-climate-normals/collection/noaa-climate-normals-netcdf/description.md
- datasets/noaa-climate-normals/collection/noaa-climate-normals-tabular/description.md
Fixes a couple things in the climate normals:
- Adds references to NODD
- Fixes link from COG to NetCDF
> [noaa-climate-normals]: fixed link to cog

- docker-compose.yml
- pctasks/ingest_task/setup.py
Keeping ingest tasks in sync with target database version.
> Upgrade pypgstac to 0.6.13

- datasets/goes/goes-glm/goes_glm.py
Sets a timeout on the `download_blob` for goes-glm.
We've observed Azure Batch tasks hanging:
```
root@306ad36c7ae3:/# py-spy dump --pid 1
Process 1: /opt/conda/bin/python /opt/conda/bin/pctasks task run blob://pctaskscommon/taskio/run/827e3fa4-be68-49c9-b8c3-3d63b31962ba/process-chunk/3/create-items/input --sas-token ... --account-url https://pctaskscommon.blob.core.windows.net/
Python v3.8.16 (/opt/conda/bin/python3.8)
Thread 0x7F8C69A78740 (active): "MainThread"
read (ssl.py:1099)
recv_into (ssl.py:1241)
readinto (socket.py:669)
_read_status (http/client.py:277)
begin (http/client.py:316)
getresponse (http/client.py:1348)
_make_request (urllib3/connectionpool.py:444)
urlopen (urllib3/connectionpool.py:703)
send (requests/adapters.py:489)
send (requests/sessions.py:701)
request …
```
> [goes-glm]: Set a timeout

- datasets/usda-cdl/collection/template.json
- datasets/usda-cdl/requirements.txt
It's an update to a static file.
> Add USDA CDL license link

- pctasks/run/pctasks/run/task/batch.py
Before this change, the BatchTaskRunner could potentially add the same job twice through the Batch API. This uses the job locks to prevent this from happening and uses the response cache to reduce the number of subsequent calls to check if a batch job exists across threads.
> Avoid multiple threads creating the same batch job

- deployment/terraform/resources/keyvault.tf
Same branch as #153, branch pushed to non-fork so CI could pass. See that PR for description.
> Change kv access settings

- deployment/bin/deploy
- deployment/bin/kv_add_ip
- deployment/bin/kv_rmv_ip
- deployment/bin/lib
- deployment/docker-compose.yml
- deployment/terraform/dev/env.sh
- deployment/terraform/staging/env.sh
Local branch of #160, with a few fixes.
> CI/CD engagement with the Key Vault Firewall

- deployment/requirements.txt
- docker-compose.yml
- pctasks/ingest_task/setup.py
Upgrades local pgstac database version to prevent race conditions on constraint creation during integration tests.
> Upgrade pgstac 0.7.3

- pctasks/core/pctasks/core/queues.py
- pctasks/dev/pctasks/dev/queues.py
- pctasks/dev/tests/test_temp_queue.py
- pctasks/ingest_task/pctasks/ingest_task/pgstac.py
- pctasks/run/pctasks/run/workflow/executor/remote.py
* Changes the default message en-/de-coding policy to None
* Ignores exists / not exists errors in temp queue creation
* Allows for more control over the queue name in TempQueue
Split from https://github.com/microsoft/planetary-computer-tasks/compare/tom/feature/low-latency, which needs this additional control over serialization policies and queue names.
> [core/dev]: Update queue settings

- pctasks/ingest_task/setup.py
This dependency doesn't appear to be used.
> Remove unused(?) smart-open

- datasets/goes/goes-glm/dataset.yaml
- datasets/goes/goes-glm/workflows/goes-glm-update.yaml
> [goes-glm]: Bump image in deployed workflow

- datasets/naip/dataset.yaml
* Bumped image
* Set app insights config
[ci skip]
> [naip]: Updates for production

- datasets/naip/dataset.yaml
- datasets/naip/naip.py
- datasets/naip/test_naip.py
* Set a timeout in `gdal_translate`
* Update regex for new file pattern
> NAIP updates

- datasets/sentinel-5p/README.md
- datasets/sentinel-5p/update.yaml
Adds an update workflow for sentinel-5p-netcdf.
> [sentinel-5p] added update workflow

- deployment/terraform/resources/function.tf
- docker-compose.yml
- pctasks/core/pctasks/core/cosmos/settings.py
- pctasks/dev/pctasks/dev/cosmosdb.py
- pctasks_funcs/WorkflowRunsCF/function.json
- pctasks_funcs/WorkflowsCF/function.json
This reverts commit 0b3dfba16e4316e6f4dd00025616a9442598bc3d.
> Revert "Set PCTASKS_COSMOSDB__TEST_CONTAINER_SUFFIX in Functions"

- deployment/bin/deploy
- deployment/docker-compose.yml
- deployment/terraform/dev/backend.tf
- deployment/terraform/dev/env.sh
- deployment/terraform/dev/main.tf
- deployment/terraform/dev/variables.tf
Moves the dev stack from a local terraform backend to a shared one. This will make it easier to build out low latency deployment features in a collaborative way with out making breaking changes to PCTest staging.
> Move dev deployment stack to shared state.

- datasets/ecmwf-forecast/Dockerfile
- datasets/ecmwf-forecast/README.md
- datasets/ecmwf-forecast/collection/description.md
- datasets/ecmwf-forecast/collection/template.json
- datasets/ecmwf-forecast/dataset.yaml
- datasets/ecmwf-forecast/ecmwf_forecast.py
- datasets/ecmwf-forecast/requirements.txt
Adds the `ecmwf-forecast` collection.
- Ingested Items into PC Test.
- Checked for equivalence to production Items by diffing an Item from the production API against one produced with this PR.
- Docker images built and pushed to both pccomponents and pccomponentstest registries.
- See the README for notes on chunk creation.
> Migrate ecmwf-forecast from etl

- scripts/cideploy
Followup to
https://github.com/microsoft/planetary-computer-tasks/actions/runs/5336427981/jobs/9672348147, which failed with
```
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.
1
Enter a value:
Error: Process completed with exit code 1.
```
We need to pass `-y` to auto-approve.
> Fixed CI Deployment

- datasets/sentinel-1-grd/README.md
- datasets/sentinel-1-grd/dataset.yaml
- datasets/sentinel-1-grd/requirements.txt
- datasets/sentinel-1-grd/s1grd.py
Updates the sentinel-1-grd collection to use the `stactools-sentinel1` package.
- Ingested Items into PC Test
- Compared the PC Test Items against existing Items pulled from the production API.
> update sentinel-1-grd to use stactools package

- datasets/sentinel-1-grd/s1grd.py
- datasets/sentinel-1-grd/test_s1grd.py
> Fixed s1-grd item writing

- pctasks/client/pctasks/client/client.py
- pctasks/client/pctasks/client/runs/options.py
- pctasks/client/pctasks/client/workflow/cli.py
- pctasks/client/pctasks/client/workflow/commands.py
- pctasks/client/pctasks/client/workflow/options.py
- pctasks/core/pctasks/core/cosmos/containers/storage_events.py
- pctasks/core/pctasks/core/models/run.py
- pctasks/dataset/pctasks/dataset/cli.py
- pctasks/dataset/pctasks/dataset/splits/cli.py
- pctasks/dataset/pctasks/dataset/utils.py
Fixes the mypy failures on main at https://github.com/microsoft/planetary-computer-tasks/actions/runs/5509181583/jobs/10041528543
> [ci]: Fixed typing issues

- datasets/ecmwf-forecast/README.md
- datasets/gbif/README.md
- datasets/goes/goes-cmi/README.md
- datasets/goes/goes-glm/README.md
- datasets/goes/goes-glm/dataset.yaml
- datasets/goes/goes-glm/workflows/goes-glm-update.yaml
- datasets/landsat/README.md
- datasets/modis/README.md
- datasets/sentinel-1-grd/README.md
- datasets/sentinel-1-rtc/README.md
- datasets/sentinel-5p/README.md
Various updates to the dataset.yaml workflows.
> Various workflow updates

- datasets/stac-geoparquet/Dockerfile
- datasets/stac-geoparquet/README.md
- datasets/stac-geoparquet/pc_stac_geoparquet.py
- datasets/stac-geoparquet/requirements.txt
- datasets/stac-geoparquet/workflow.yaml
This adds a workflow for generating the Planetary Computer's [stac-geoparquet](https://planetarycomputer.microsoft.com/docs/quickstarts/stac-geoparquet/) files.
> Added stac-geoparquet workflow

- datasets/goes/goes-glm/streaming.yaml
- deployment/bin/deploy
- deployment/bin/lib
- workflows/streaming-ingest.yaml
* Added a "streaming-ingest" workflow
* Deployment script updates
* Bump goes-glm version
> Low latency fixups

- datasets/gbif/dataset.yaml
- datasets/goes/goes-cmi/dataset.yaml
- datasets/goes/goes-glm/README.md
- datasets/goes/goes-glm/dataset.yaml
- datasets/modis/dataset.yaml
- datasets/noaa-climate-normals/dataset.yaml
- datasets/noaa-mrms-qpe/README.md
- datasets/noaa-mrms-qpe/dataset.yaml
- datasets/noaa_nclimgrid/dataset.yaml
- datasets/sentinel-3/README.md
- datasets/sentinel-3/dataset.yaml
- datasets/sentinel-5p/dataset.yaml
This adds the Application Insights connection string to more datasets. This will let us monitor the STAC item creation time for more workflows.
These have been deployed.
> Add AI Connection String to more datasets

- datasets/ecmwf-forecast/README.md
- datasets/ecmwf-forecast/streaming.yaml
- deployment/terraform/resources/storage_account.tf
- pctasks_funcs/StorageEventsCF/__init__.py
Adds a streaming workflow for ecmwf-forecast.
> Added ecmwf-forecast

- deployment/terraform/resources/vnet.tf
Restricts the destination port ranges in the Virtual Network used with Azure Batch.
> Updated nsg for vnet

- deployment/terraform/batch_pool/main.tf
This updates the rule of the NSG that's generated by Azure Batch.
> Update batch NSG rules

- Dockerfile.dev
- pctasks/dataset/pctasks/dataset/streaming.py
- pctasks/dev/setup.py
- pctasks/ingest_task/pctasks/ingest_task/streaming.py
- pctasks/server/setup.py
- pctasks/server/tests/routes/test_run.py
- pctasks/task/pctasks/task/streaming.py
See [published vulnerability report](https://github.com/advisories/GHSA-74m5-2c7w-9w3x). This PR updates the minimum version of FastAPI to the latest version.
Depending on pipelines to catch regressions.
> Update FastAPI version to indirectly update starlette

- deployment/terraform/resources/aks.tf
Enabling the AKS image cleaner.
This property has been deployed in other clusters and needs to be enabled in pctasks.
> Add image cleaner feature to AKS cluster

- datasets/usgs-lidar/README.md
- datasets/usgs-lidar/concatenate_csvs.py
- datasets/usgs-lidar/lidar_audit.py
- datasets/usgs-lidar/requirements.txt
- datasets/usgs-lidar/workflow.yaml
Tools to address [this data quality issue](https://github.com/microsoft/PlanetaryComputer/issues/323).
I have run this pipeline.
> USGS Lidar dataset audit workflow

- datasets/noaa-cdr/hang.py
Removing credentials from source code.
> Read NOAA access token from environment variable

- .github/workflows/publish-func-package-dev.yml
- .github/workflows/publish-func-package.yml
See failure at https://github.com/microsoft/planetary-computer-tasks/actions/runs/9116458197
Similar to
https://github.com/microsoft/planetary-computer-tasks/pull/293.
> Fixed publish function package workflow

- pctasks/core/setup.py
- pctasks/server/Dockerfile
- pctasks/server/setup.py
Small security patching and image change for pctasks-server
> Security patching and image updates

- RELEASING.md
Adds a short doc on how to create releases (primarily for the Federated Identity Credential & tags)
> Added RELEASING.md

- deployment/helm/argo-values.yaml
- deployment/terraform/resources/storage_account.tf
- docker-compose.yml
- docs/development/deploying.md
Bumps to latest version, security patching.
> Bumps the ACR vendored argo image versions

- deployment/helm/published/pctasks-server/templates/deployment.yaml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Remove the definition of cosmosdb key from helm chart values
